### PR TITLE
Website Image Optimization done #1

### PR DESCRIPTION
**Pull request by ronitsharma03**
Converted all the images to Webp

### CODE REVIEW

**Comment by abdul-muyeed** [comment]
Remove this typo.

**Review by abdul-muyeed — CHANGES_REQUESTED** [review]
Found a typo in index.html on line 302.

**Comment by ronitsharma03** [comment]
Fixed the typo!

**Review by abdul-muyeed — APPROVED** [review]
OK, I will pr this.

**Comment by ronitsharma03** [comment]
Any other issue to resolve?

**Pull request merged**
